---
- name: Set awx_secret_key
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^\s*awx_secret_key=.*$'
    line: "awx_secret_key={{ awx_secret_key }}"
    state: present

- name: Set pg_password
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^\s*pg_password=.*$'
    line: "pg_password={{ pg_password }}"
    state: present

- name: Set default_admin_user
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^#?\s*default_admin_user=.*$'
    line: "default_admin_user={{ default_admin_user }}"
    state: present

- name: Set default_admin_password
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^#?\s*default_admin_password=.*$'
    line: "default_admin_password={{ default_admin_password }}"
    state: present
